version: '3.9'
services:
  Banco_teste:
    image: postgres:16
    environment:
      POSTGRES_USER: Locals
      POSTGRES_PASSWORD: Locals
      POSTGRES_DB: Locals
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  kafka-connect:
      image: s3_sink:1.0
      environment:
        CONNECT_BOOTSTRAP_SERVERS: broker:9092
        CONNECT_GROUP_ID: kafka-connect-s3
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-configs
        CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-offsets
        CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-status
        CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
        CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
        AWS_ACCESS_KEY_ID: "****************"
        AWS_SECRET_ACCESS_KEY: "****************"
        CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      volumes:
        - ./s3-sink-config:/etc/kafka-connect/s3-sink
      ports:
        - "8083:8083" 
      networks:
        - kafka-net
      depends_on:
        - broker
  broker:
    image: bitnami/kafka:latest
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - kafka-net
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - broker
    ports:
      - "8080:8080"
    networks:
      - kafka-net
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "broker:9092"
  app:
    image: klockrc/api-json-scala:1.0
    depends_on:
      - broker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
    ports:
      - "9090:9090"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
